server:
  port: 2222

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_master?useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: Zhen.com123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: caffeine
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

ocr:
  service: chaojiyingOcrService
  third:
    aliyun:
      appcode:
    chaojiying:
      user:
      pass:
      softid: 000000

logging:
  file:
    name: ./logs/stock-service.log
  logback:
    rollingpolicy:
      max-history: 30
  level:
    root: info
    org.springfromework.web: info
    org.springframework.jdbc: debug
